# Custom Language File for Launcher Customizer

[ejs.app]
title = "Minerica launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/djl987645/Minerica-Launcher"
mediaWikiURL = "https://minerica.notion.site/ac822f0cb16c45249888f01ac44c8113"
mediaMapURL = "http://minerica.kr:8123/"
mediaDiscordURL = "https://discord.gg/XYcy5KJnr4"
mediaInstagramURL = "https://www.instagram.com/mine_square"

[ejs.settings]
sourceGithubLink = "https://github.com/djl987645/Minerica-Launcher"
supportLink = "https://github.com/djl987645/Minerica-Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO Minerica!"
welcomeDescription = "대학교 마인크래프트 서버인 마인에리카에 어서오세요!"
welcomeDescCTA = "마크에서도 캠퍼스 라이프를 즐기세요!"
